name: jolutrip_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  dio: ^5.9.2
  get_it: ^9.2.1
  go_router: ^17.2.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  visibility_detector: ^0.4.0+2
  dartz: ^0.10.1
  video_player: ^2.11.1
  flutter_secure_storage: ^10.3.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  google_fonts: ^8.1.0
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  share_plus: ^13.2.0
  image_picker: ^1.2.3
  flutter_native_splash: 2.4.7
  permission_handler: ^12.0.3
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/2gis.png
    - assets/icons/beeline.png
    - assets/icons/glovo.png
    - assets/icons/kicb.png
    - assets/icons/mbank.png
    - assets/icons/mega.jpg
    - assets/icons/namba.webp
    - assets/icons/o.png
    - assets/icons/optima.jpg
    - assets/icons/yandex.png
    - assets/icons/maps.png
    - assets/icons/namba_taxi.png
    - assets/icons/booking.jpg
    - assets/icons/elsom.png
    - assets/icons/gorod.png
    - assets/icons/indrive.webp
    - assets/icons/whatsapp.png
